package Models;
// Generated 12 oct. 2019 20:12:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sites generated by hbm2java
 */
public class Sites  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String description;
     private float lat;
     private float lng;
     private Set siteImgses = new HashSet(0);

    public Sites() {
    }

	
    public Sites(String nom, String description, float lat, float lng) {
        this.nom = nom;
        this.description = description;
        this.lat = lat;
        this.lng = lng;
    }
    public Sites(String nom, String description, float lat, float lng, Set siteImgses) {
       this.nom = nom;
       this.description = description;
       this.lat = lat;
       this.lng = lng;
       this.siteImgses = siteImgses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public float getLat() {
        return this.lat;
    }
    
    public void setLat(float lat) {
        this.lat = lat;
    }
    public float getLng() {
        return this.lng;
    }
    
    public void setLng(float lng) {
        this.lng = lng;
    }
    public Set getSiteImgses() {
        return this.siteImgses;
    }
    
    public void setSiteImgses(Set siteImgses) {
        this.siteImgses = siteImgses;
    }




}


